scripts {
  APS {
    APS_testmode {
      scriptClass = aps.Testmode
    }
    APS_software_only_mode {
      scriptClass = aps.ApsSoftwareOnlyMode
    }
    apsPeasSequencerA_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerA
    }
    apsPeasSequencerB_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerB
    }
    apsPeasSequencerC_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerC
    }
    apsPeasSequencerD_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerD
    }
  }
}
