scripts {
  APS {
    APS_testmode {
      scriptClass = aps.Testmode
    }
    APS_software_only_mode {
      scriptClass = aps.ApsSoftwareOnlyMode
    }
    apsPeasSequencerA_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerA
    }
    apsPeasSequencerB_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerB
    }
    apsPeasSequencerC_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerC
    }
    apsPeasSequencerD_SoftwareOnlyMode {
      scriptClass = aps.PeasSequencerD
    }
    
    apsPeasSequencerA_ApsStandaloneMode {
      scriptClass = aps.PeasSequencerA
    }
    apsPeasSequencerB_ApsStandaloneMode {
      scriptClass = aps.PeasSequencerB
    }
    apsPeasSequencerC_ApsStandaloneMode {
      scriptClass = aps.PeasSequencerC
    }
    apsPeasSequencerD_ApsStandaloneMode {
      scriptClass = aps.PeasSequencerD
    }
    
    
    icsSequencer_IcsOperational {
      scriptClass = aps.IcsSequencer
    }

    icsSequencer_IcsSimulator {
      scriptClass = aps.IcsSequencer
    }

    pitSequencer_PitOperational {
      scriptClass = aps.PitSequencer
    }

    pitSequencer_PitSimulator {
      scriptClass = aps.PitSequencer
    }

    
  }
}
